---
title: Legge til en lyd fra biblioteket
hero_image: images / banner.png
description: Slik legger du til en lyd på Skrapeløpet
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "ripe"
steps:
  - 
    title: Legg til en lyd på spritet ditt
