---
title: Tilføjelse af en lyd fra biblioteket
hero_image: images/banner.png
description: Sådan tilføjes en lyd til din Scratch-sprite
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Tilføj en lyd til din sprite
