---
title: Adicionar um som da livraria
hero_image: imagens / banner.png
description: Como adicionar um som ao teu actor do Scratch
original_url:
theme: protótipo cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adiciona um som ao teu actor
