---
title: Добавяне на звук от библиотеката
hero_image: изображения / banner.png
description: Как да добавите звук към вашия Scratch Sprite
original_url:
theme: сс-прототип
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "драскотина"
steps:
  - 
    title: Добавете звук към вашия спрайт
