---
title: Hang hozzáadása a könyvtárból
hero_image: images/banner.png
description: Hogyan adhatsz hozzá hangot a Scratch szereplődhöz
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Adj hozzá hangot a szereplődhöz
