---
title: Hang hozzáadása a könyvtárból
hero_image: images / banner.png
description: Hogyan adhat hozzá hangot a Scratch sprite-hez?
original_url:
theme: cc-prototípus
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "karcolás"
steps:
  - 
    title: Hang hozzáadása a sprite-hez
