---
title: 라이브러리에서 사운드 추가
hero_image: images / banner.png
description: Scratch sprite에 사운드를 추가하는 방법
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "Scratch"
steps:
  - 
    title: 스프라이트에 사운드 추가하기
