---
title: Lägger till ett ljud från biblioteket
hero_image: images / banner.png
description: Så här lägger du till ett ljud i din Scratch-sprite
original_url:
theme: cc-prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "repa"
steps:
  - 
    title: Lägg till ett ljud på din sprite
